"""
BharatRAG — Full Hindi RAG Example
Shows how to use BharatRAG to evaluate a Hindi RAG system.
"""

from bharatrag import evaluate
from bharatrag.utils.helpers import pretty_print_results


# ── Simulated RAG System Output ───────────────────────────────
# In a real system, these would come from:
# - questions: user input
# - contexts: retrieved from your vector DB
# - answers: generated by your LLM

questions = [
    "पीएम किसान योजना में कितने रुपये मिलते हैं?",
    "आयुष्मान भारत योजना क्या है?",
    "उज्ज्वला योजना किसके लिए है?",
]

contexts = [
    [
        "प्रधानमंत्री किसान सम्मान निधि योजना के तहत किसानों को प्रति वर्ष 6000 रुपये मिलते हैं।",
        "यह राशि तीन किश्तों में सीधे बैंक खाते में जमा होती है।"
    ],
    [
        "आयुष्मान भारत योजना के तहत पात्र परिवारों को 5 लाख रुपये तक का स्वास्थ्य बीमा मिलता है।",
        "इस योजना से 10 करोड़ गरीब परिवार लाभान्वित होते हैं।"
    ],
    [
        "प्रधानमंत्री उज्ज्वला योजना गरीबी रेखा से नीचे की महिलाओं को मुफ्त एलपीजी कनेक्शन देती है।",
        "इसका उद्देश्य ग्रामीण महिलाओं को धुएं से मुक्त रसोई देना है।"
    ],
]

# Good answers — grounded in context
good_answers = [
    "पीएम किसान योजना में किसानों को प्रति वर्ष 6000 रुपये तीन किश्तों में मिलते हैं।",
    "आयुष्मान भारत योजना में पात्र परिवारों को 5 लाख रुपये तक का स्वास्थ्य बीमा मिलता है।",
    "उज्ज्वला योजना गरीबी रेखा से नीचे की महिलाओं के लिए है और उन्हें मुफ्त एलपीजी देती है।",
]

# Bad answers — hallucinated
bad_answers = [
    "पीएम किसान योजना में 20000 रुपये मिलते हैं।",
    "आयुष्मान भारत योजना केवल सरकारी कर्मचारियों के लिए है।",
    "उज्ज्वला योजना शहरी महिलाओं के लिए बनाई गई थी।",
]


# ── Evaluate Good Answers ─────────────────────────────────────
print("=" * 50)
print("Evaluating CORRECT answers...")
print("=" * 50)

good_results = evaluate(
    questions=questions,
    contexts=contexts,
    answers=good_answers,
    language="hindi"
)
pretty_print_results(good_results)


# ── Evaluate Bad Answers ──────────────────────────────────────
print("\n" + "=" * 50)
print("Evaluating HALLUCINATED answers...")
print("=" * 50)

bad_results = evaluate(
    questions=questions,
    contexts=contexts,
    answers=bad_answers,
    language="hindi"
)
pretty_print_results(bad_results)


# ── Comparison ────────────────────────────────────────────────
print("\n" + "=" * 50)
print("COMPARISON")
print("=" * 50)
print(f"  Correct answers overall:     {good_results['overall']}")
print(f"  Hallucinated answers overall: {bad_results['overall']}")
diff = round(good_results['overall'] - bad_results['overall'], 4)
print(f"  Difference:                  +{diff}")
print("\nBharatRAG correctly scored correct answers higher! ✅")