"""
BharatRAG — Full Telugu RAG Example
Shows how to use BharatRAG to evaluate a Telugu RAG system.
"""

from bharatrag import evaluate
from bharatrag.utils.helpers import pretty_print_results


# ── Simulated RAG System Output ───────────────────────────────
# In a real system, these would come from:
# - questions: user input
# - contexts: retrieved from your vector DB
# - answers: generated by your LLM

questions = [
    "పీఎం కిసాన్ పథకంలో రైతులకు ఎంత డబ్బు లభిస్తుంది?",
    "ఆయుష్మాన్ భారత్ పథకం ఏమిటి?",
    "ఉజ్వల యోజన ఎవరి కోసం?",
]

contexts = [
    [
        "ప్రధానమంత్రి కిసాన్ సమ్మాన్ నిధి పథకం కింద రైతుల కుటుంబాలకు సంవత్సరానికి 6000 రూపాయలు లభిస్తుంది.",
        "ఈ రూపాయలు 2000 చొప్పున మూడు వాయిదాల్లో బ్యాంకు ఖాతాకు వెళ్లాయి."
    ],
    [
        "ఆయుష్మాన్ భారత్ పథకం కింద అర్హులైన కుటుంబాలకు 5 లక్షల రూపాయల వరకు ఆరోగ్య బీమా లభిస్తుంది.",
        "ఈ పథకం దేశంలోని లక్షల పేద కుటుంబాలను సహాయ చేస్తుంది."
    ],
    [
        "ప్రధానమంత్రి ఉజ్వల యోజన దారిద్ర్య రేఖకు దిగువన ఉన్న మహిళలకు ఉచిత ఎల్పీజీ కనెక్షన్ అందిస్తుంది.",
        "ఈ పథకం గ్రామీణ మహిళలకు పొగరహిత వంటగది లభించేందుకు సహాయం చేస్తుంది."
    ],
]

# Good answers — grounded in context
good_answers = [
    "పీఎం కిసాన్ పథకంలో రైతులకు సంవత్సరానికి 6000 రూపాయలు మూడు వాయిదాల్లో లభిస్తాయి.",
    "ఆయుష్మాన్ భారత్ పథకం కింద అర్హులైన కుటుంబాలకు 5 లక్షల రూపాయల వరకు ఆరోగ్య బీమా లభిస్తుంది.",
    "ఉజ్వల యోజన దారిద్ర్య రేఖకు దిగువన ఉన్న మహిళల కోసం ఉచిత ఎల్పీజీ కనెక్షన్ ఇచ్చే పథకం.",
]

# Bad answers — hallucinated
bad_answers = [
    "పీఎం కిసాన్ పథకంలో రైతులకు సంవత్సరానికి 20000 రూపాయలు లభిస్తాయి.",
    "ఆయుష్మాన్ భారత్ పథకం ప్రభుత్వ ఉద్యోగుల కోసం మాత్రమే.",
    "ఉజ్వల యోజన పట్టణ మహిళల కోసం.",
]


# ── Evaluate Good Answers ─────────────────────────────────────
print("=" * 50)
print("Evaluating CORRECT answers...")
print("=" * 50)

good_results = evaluate(
    questions=questions,
    contexts=contexts,
    answers=good_answers,
    language="telugu"
)
pretty_print_results(good_results)


# ── Evaluate Bad Answers ──────────────────────────────────────
print("\n" + "=" * 50)
print("Evaluating HALLUCINATED answers...")
print("=" * 50)

bad_results = evaluate(
    questions=questions,
    contexts=contexts,
    answers=bad_answers,
    language="telugu"
)
pretty_print_results(bad_results)


# ── Comparison ────────────────────────────────────────────────
print("\n" + "=" * 50)
print("COMPARISON")
print("=" * 50)
print(f"  Correct answers overall:     {good_results['overall']}")
print(f"  Hallucinated answers overall: {bad_results['overall']}")
diff = round(good_results['overall'] - bad_results['overall'], 4)
print(f"  Difference:                  +{diff}")
print("\nBharatRAG correctly scored correct answers higher! ✅")
